---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bottlerocket-bootstrap-instance-id
  description: Bootstrap container for Bottlerocket OS to populate the instance ID to /var/lib/cloud/data/instance-id for Datadog, etc. to consume when access to IMDS is disabled.
  annotations:
    github.com/project-slug: Updater/bottlerocket-bootstrap-instance-id
spec:
  type: container-image
  owner: group:devops
